### ISSUE TITLE
Coherent light in DPM

### ISSUE THREAD

**Issue by MFLakatos** [arXiv/html_feedback#1006]
### Description

"Although interferences are involved in CGM/QLSI, DPM, FPM and SLIM, these techniques do not need the use of coherent light sources"I think DPM needs coherent light. Bhaduri 2014 talk about that in "Diffraction phase microscopy: Principles and applications in materials and lifesciences" 4.2bSpatial Coherence
Great work!

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

a6a6e840-12ee-4e48-b806-b53af330bee1

### Paper URL

https://arxiv.org/html/2403.11930v1

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly, as they likely do not track issues here. This space is for tracking issues with the experimental HTML format.
