### ISSUE TITLE
 The URL address of the provided dataset cannot be opened

### ISSUE THREAD

**Issue by tianpengzhang123** [arXiv/html_feedback#1053]
### Description

The URL address of the provided dataset cannot be opened

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

ec8cb457-f9df-490c-9fc3-db9c7704d1a8

### Paper URL

https://arxiv.org/html/2403.10369v2

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors for issues with the main text. This repository only tacks the quality of the experimental HTML format.
