### ISSUE TITLE
 https://arxiv.org/html/2302.03038v2

### ISSUE THREAD

**Issue by xim2016** [arXiv/html_feedback#1069]
### Description

learnable PE and sinusoid PE. Learnable PE is introduced in ViT (Dosovitskiy et al., 2020), where it learns a positional encoding for each individual position. Sinusoid PE is proposed in vanilla transformer (Vaswani et al., 2017), originally designed for sequential data, while it can be extended to 2-dimensional space (Carion et al., 2020).

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

cb57dc1b-386d-495b-a1fc-766534080790

### Paper URL

https://arxiv.org/html/2302.03038v2

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format.
