### ISSUE TITLE
 Pdf is 1 page and nonsense while html is correctly

### ISSUE THREAD

**Issue by Aphexus** [arXiv/html_feedback#1102]
### Description

"Download PDF" is producing nonsense while html is correct.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

93ca13de-f8bf-45be-b298-8e8523485818

### Paper URL

https://arxiv.org/html/2404.15899v1

### Browser

Firefox/111.0

### Device Type

Desktop

**Comment by dginev** [comment]
Since the focus in this repository is on the HTML format, closing here. Feel free to reopen with more details if relevant.
