### ISSUE TITLE
 misspelled

### ISSUE THREAD

**Issue by MaximilianVW99** [arXiv/html_feedback#1116]
### Description

Huamn instead of Human

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

7dae132b-8e0c-4ccd-a2ed-261db56fd5c8

### Paper URL

https://arxiv.org/html/2402.14852v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by VladimirAlexiev** [comment]
Well @MaximilianVW99 , the misspelling is made by the authors, see https://arxiv.org/abs/2402.14852v1.
So this is not a bug of the HTML renderer.
