### ISSUE TITLE
spell check in  https://arxiv.org/html/2404.19756v1#S2.F2

### ISSUE THREAD

**Issue by Giaco-am** [arXiv/html_feedback#1144]
Hello,
directly below Eq. 2.2, the word 'detailed' is misspelled as in:  'where the functions [...] have trainable parameters, as detaild below.

**Comment by chrisjcameron** [comment]
This report would be better directed to the paper authors, as it is unlikely to have come about due to a technical issue with the LaTeX to HTML conversion feature. I did notify the author using the [view email] link available (to all logged in readers) on the article abstract page.
