### ISSUE TITLE
 the formula letter $v$ should be replaced by $v_f$

### ISSUE THREAD

**Issue by DAVIDSCG** [arXiv/html_feedback#1150]
### Description

According to the description of the formula below, it can be seen that.

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

d9faf5b0-5026-4804-b0f8-541dcad63f02

### Paper URL

https://arxiv.org/html/2403.04115v2

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the author for corrections to the text.

This repository only tracks the quality of the experimental HTML format.
