### ISSUE TITLE
 typo

### ISSUE THREAD

**Issue by Chain123** [arXiv/html_feedback#1162]
### Description

using use 

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

b8649bd0-f232-4cb0-9719-674f6485b307

### Paper URL

https://arxiv.org/html/2403.10131v1

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the author with corrections to the text.

This repository only tracks the quality of the experimental HTML format.
