### ISSUE TITLE
 PDF is corrupt

### ISSUE THREAD

**Issue by blue-j** [arXiv/html_feedback#1166]
### Description

https://arxiv.org/html/2403.03594v1

PDF download is rejected by Adobe Acrobat Pro with this message: "An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem."  The PDF display itself is blank, with bounding boxes only around links.

### (Optional:) Please add any files, screenshots, or other information here.

![Screenshot 2024-05-04 at 2 20 57 PM](https://github.com/arXiv/html_feedback/assets/3990142/9d72829e-04d0-45a0-aaec-4c981d383137)

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

f48bce43-2918-4be9-9fa8-266b4405ef31

### Paper URL

https://arxiv.org/html/2403.03594v1

### Browser

Chrome/124.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
I believe this has been independently resolved?

Also, this repository only tracks the quality of the experimental HTML format. Thanks!
