### ISSUE TITLE
 The font in HTML

### ISSUE THREAD

**Issue by SCULX** [arXiv/html_feedback#1200]
### Description

In the HTML, the font is not comfortable for browsing, so may it will be some choices for the different font

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

880ef671-2b98-4a2f-994e-ad3a48b9b4a8

### Paper URL

https://arxiv.org/html/2402.01763v1

### Browser

Chrome/124.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for the report - we have changed to `rival-sans`
