### ISSUE TITLE
 Misspelling 

### ISSUE THREAD

**Issue by loremendez** [arXiv/html_feedback#1222]
### Description

Provably should be changed by probably

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

0158f53f-bcaf-4c22-b6a1-1cf267df2c47

### Paper URL

https://arxiv.org/html/2402.08871v1

### Browser

Safari/604.1

### Device Type

iOS

**Comment by dginev** [comment]
Please contact the author with corrections to the text.

This repository only tracks the quality of the experimental HTML format.
