### ISSUE TITLE
Stealing from creators

### ISSUE THREAD

**Issue by skittlesisbored** [arXiv/html_feedback#1287]
### Description

How is stealing 42 million animations from around the world and is distributing them under the name "AI research dataset" okay? Pretty scummy behaviour to profit from AI and not be returning any of it to the animation creators at all. Absolutily vile.

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

0324a7b7-2d28-48bf-b4cc-d054427bb429

### Paper URL

https://arxiv.org/html/2405.07425v1

### Browser

Chrome/124.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Please submit an issue in the user support or code of conduct contact points. See https://info.arxiv.org/help/contact.html
