### ISSUE TITLE
 Copyrighted works, no citation or attribution

### ISSUE THREAD

**Issue by CosmicMatt** [arXiv/html_feedback#1289]
### Description

This dataset is built upon almost exclusively copyrighted works, and does not even attribute the creators or rights holders within the paper or the github itself.

### (Optional:) Please add any files, screenshots, or other information here.

![x1](https://github.com/arXiv/html_feedback/assets/10132408/dc24cb2a-372e-4614-90c0-65b451b410c7)
![x2](https://github.com/arXiv/html_feedback/assets/10132408/69572fed-965b-4991-bc5f-a7e92150129a)

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

2ebb8c73-c57e-49bb-a9d6-c213555da0b9

### Paper URL

https://arxiv.org/html/2405.07425v1

### Browser

Firefox/126.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Please submit an issue in the user support or code of conduct contact points. See https://info.arxiv.org/help/contact.html
