### ISSUE TITLE
 Massive plagiarism

### ISSUE THREAD

**Issue by angelleal21** [arXiv/html_feedback#1290]
### Description

Pay the people whose art and animation you've stolen to train this.

### (Optional:) Please add any files, screenshots, or other information here.

How are people going to opt-out of this if they don't know their animation is being used to be trained?

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

7ad48dea-f7ae-49f4-a275-d4a88979758c

### Paper URL

https://arxiv.org/html/2405.07425v1

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Please submit an issue in the user support or code of conduct contact points. See https://info.arxiv.org/help/contact.html
