### ISSUE TITLE
 The google scholar didn't detect the change of bibtex

### ISSUE THREAD

**Issue by shibowing** [arXiv/html_feedback#1299]
### Description

Hi all, 

I updated a new version of this paper and updated the authorship. However, it seems that Google Scholar didn't detect the change of authorship. Therefore, I manually updated Bibtex. However, when I looked up this paper in Google Scholar, it still uses the old Bibtex. The arxiv actually provides the correct BibTeX. However, it seems it wasn't detected from the Google Scholar side. Do you know how to solve this problem?  Thank you very much for your help! 

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

c5198402-8a6b-48d4-91c5-c9dbee5c45df

### Paper URL

https://arxiv.org/html/2307.07607v4

### Browser

Chrome/110.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This may be a very good question for the Google Scholar team.

In any case, this repository only tracks the quality of the experimental HTML format, so we're a bit off-topic...
