### ISSUE TITLE
 PDF not working

### ISSUE THREAD

**Issue by 42elenz** [arXiv/html_feedback#1313]
### Description

The Pdf of this is not working. I can not download the pdf

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

c6a96efa-e40a-4f00-9462-9c5fa367338e

### Paper URL

https://arxiv.org/html/2312.07353v3/

### Browser

Chrome/125.0.0.0

### Device Type

Windows

**Comment by chrisjcameron** [comment]
dev note: the html link the paper adds a backslash on the end of the URL

**Comment by chrisjcameron** [comment]
The html page should be checked on or after 5/23 to see if the rebuild on new release resolved the URL issue.

**Comment by chrisjcameron** [comment]
@42elenz, can you help me track down where you found the URL with the trailing backslash (e.g. https://arxiv.org/html/2312.07353v3/ vs. https://arxiv.org/html/2312.07353v3)? Is the training slash version of the URLs are being published somewhere, I would like to investigate further.

**Comment by 42elenz** [comment]
@chrisjcameron Hi Chris! Thx for looking into the issue. I was just searching for "CLIP in medical imaging: A comprehensive survey"  in google. The first 2 Links had the broken reference to the pdf. This is not like that anymore. I tried again (Searching on google, clicking on the first result and then pdf). Now it works.

**Comment by chrisjcameron** [comment]
Thanks! We will have a few adjustments so the PDF link is more robust to backslashes in the originating URL. Thanks for taking the time to report this and help investigate!

**Comment by dginev** [comment]
Looks resolved, thanks!
