### ISSUE TITLE
 Author name typo "Macdonald"

### ISSUE THREAD

**Issue by dvalenciar** [arXiv/html_feedback#1314]
### Description

It should be Bruce Macdonald

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

4f76025b-0939-4ec6-a39c-748f2a4f0dc8

### Paper URL

https://arxiv.org/html/2405.02576v1

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This is the same in the PDF I believe? Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format.
