### ISSUE TITLE
there is no space in the text between the sentences

### ISSUE THREAD

**Issue by Say1ts** [arXiv/html_feedback#1317]
### Description

there is no space in the text between the sentences

### (Optional:) Please add any files, screenshots, or other information here.

![Снимок экрана 2024-05-23 110035](https://github.com/arXiv/html_feedback/assets/74491848/766705b2-9bc5-4b0f-9cae-0cabaa9803fd)

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

a4f9c777-33c2-4cd5-96a0-6e057bbd37f6

### Paper URL

https://arxiv.org/html/2312.10997v5

### Browser

Chrome/125.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This is the same in the PDF I believe? Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format.
