### ISSUE TITLE
 Figure 3 has an incorrect aspect ratio and appears severly distorted

### ISSUE THREAD

**Issue by BenWibking** [arXiv/html_feedback#135]
### Description

The aspect ratio is badly wrong and is so squashed it makes it more difficult to interpret.

### (Optional:) Please add any files, screenshots, or other information here.

<img width="867" alt="Screenshot 2023-12-18 at 8 03 16 PM" src="https://github.com/arXiv/html_feedback/assets/1781919/ca2b04d6-f042-4da8-89ef-97f066f6dce4">

### (Required) What is this issue most closely related to? Select one.

Figures

### Internal issue ID

61ec82dd-4ca4-4e64-80cd-f876c75844a6

### Paper URL

https://browse.arxiv.org/html/2312.09567v1

### Browser

Chrome/120.0.0.0

### Device Type

Desktop

**Comment by SamAdamDay** [comment]
Same issue with Figure 3 here: https://browse.arxiv.org/html/2305.10391v2#S3.F3

In the source it uses `\includegraphics[width=0.6\linewidth]`. In the HTML the height and width are manually set to the same thing, which is incorrect

**Comment by SBBCornell** [comment]
The image aspect ratios issue has been fixed. Thank you for your report, we appreciate it.
