### ISSUE TITLE
figs 4,5 wrong aspect ratio

### ISSUE THREAD

**Issue by ginsparg** [arXiv/html_feedback#143]
### Description

figs 4,5 are incorrectly stretched to fill the full horizontal width, so badly distorted. 
the boundaries should be circles, not ellipses

### (Optional:) Please add any files, screenshots, or other information here.

![fig4](https://github.com/arXiv/html_feedback/assets/56209291/49b38841-3af5-4d2b-aa8e-c4038d7facd9)
![fig5](https://github.com/arXiv/html_feedback/assets/56209291/cacef488-394c-451d-94bf-14444012eb9e)

### (Required) What is this issue most closely related to? Select one.

Figures

### Internal issue ID

35e13cd6-b705-41cf-b481-aa4d7762bc1b

### Paper URL

https://browse.arxiv.org/html/2312.08434v2

### Browser

Chrome/116.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Triage note: this is purely a CSS issue that has to do with the `.ltx_img_square` rules. 

Adaptive resizing can get tricky...

**Comment by SBBCornell** [comment]
The image aspect ratios issue has been fixed in most instances, including this one. We appreciate the report.
