### ISSUE TITLE
 Figures stretched.

### ISSUE THREAD

**Issue by dhairyaiitb** [arXiv/html_feedback#145]
### Description

Some of the figures have gotten stretched/compressed. For eg: Fig. 4, Fig. 5, and Fig. 7. 

### (Required) What is this issue most closely related to? Select one.

Figures

### Internal issue ID

41045423-979b-46e0-b3be-a312640231e1

### Paper URL

https://services.arxiv.org/html/submission/5296233/view

### Browser

Chrome/120.0.0.0

### Device Type

Desktop

**Comment by SBBCornell** [comment]
The image aspect ratios issue has been fixed. Thank you for your report, we appreciate it.
