### ISSUE TITLE
 404

### ISSUE THREAD

**Issue by Dareczin** [arXiv/html_feedback#1482]
### Description

link does not work

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

c5cc5dee-aa72-4f7f-afdf-22f0c1c2af21

### Paper URL

https://arxiv.org/html/2312.00692v1/

### Browser

Chrome/125.0.0.0

### Device Type

PC

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format.
