### ISSUE TITLE
Improve article : 2307.11045v1 (all articles)

### ISSUE THREAD

**Issue by cbf66** [arXiv/html_feedback#15]
## Describe the issue

**Description**: In dark mode if you minimize the TOC, and then unminimize it, the TOC background is white.

Feel free to attach a screenshot (or document) link below: 

## Auto Fill Data - !!! Please do not edit below this line !!!
----------------------------------------------------------------------------------------

Id: 3f79fe7b-9f9f-4ff6-aca0-15b4069e347b

**Comment by chrisjcameron** [comment]
This appears to be resolved
