### ISSUE TITLE
Fossil Fuel Emissions: 	  37 GtCO2 per year 2.97% of total

### ISSUE THREAD

**Issue by BHRomo** [arXiv/html_feedback#1524]
Photosynthesis: 		440 GtCO2 per year 35.28%
Ocean Degassing: 		330 GtCO2 per year 26.47%
Soil Respiration: 		220 GtCO2 per year 17.64%
Plant Respiration: 		220 GtCO2 per year 17.64%
Fossil Fuel Emissions: 	  37 GtCO2 per year 2.97%
~Total:			         1,247 GtCO2 per year 100%

I have a serios question, does the annual increments considers 2.5 ppmv include all sources, or just enthropogenic ones?
Since man made or anthropogenic contributions are ~ 2.97% of the total earth emissions this result is confusing to me, since the absurdity of reducing absolute all anthropogenic CO2 emissions will only refer to that ~ 2.97% therefore the reduction of the total earth atmospheric temperature will reflect a change in that minuscule percentage.
Unless all emissions and forcing remained univariable. I do not think so.

**Comment by BHRomo** [comment]
Thank you!

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format.
