### ISSUE TITLE
 pet-sql of spider leaderboard

### ISSUE THREAD

**Issue by kevinew** [arXiv/html_feedback#1580]
### Description

hello, recently  appeared  a  pet-sql  , it have 0.87 score in spider , you can add it to the figure 2https://arxiv.org/html/2403.09732v3

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

49ce4189-fd3d-438d-8d36-1f548157b6b9

### Paper URL

https://arxiv.org/html/2406.01265v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format.
