### ISSUE TITLE
 Fonts are inconsistent

### ISSUE THREAD

**Issue by thesamuel** [arXiv/html_feedback#1615]
### Description

The combination of serif fonts for titles and sans serif fonts for paragraph text look weird and distracting. I find myself avoiding the HTML feature entirely because of these formatting inconsistencies.

### (Optional:) Please add any files, screenshots, or other information here.

Example: https://arxiv.org/html/2403.04769v1

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

78f80653-fd95-41dc-8e36-3d4e133612d2

### Paper URL

https://arxiv.org/html/2403.04769v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
We have now standardized to `rival-sans`, thank you for the report.
