### ISSUE TITLE
Correction of typos

### ISSUE THREAD

**Issue by SuminSSon** [arXiv/html_feedback#1620]
### Description

exosystem -> ecosystem

### (Optional:) Please add any files, screenshots, or other information here.

![image](https://github.com/arXiv/html_feedback/assets/56192209/52df31eb-8e6f-4a89-bf95-443edf305ca7)

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

045470f2-4c9e-4784-9cef-985d586eb468

### Paper URL

https://arxiv.org/html/2401.04552v1

### Browser

Firefox/127.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
