### ISSUE TITLE
 Ablation experiment

### ISSUE THREAD

**Issue by xxd2977** [arXiv/html_feedback#1644]
### Description

There seems to be no ablation experiments on feature adapters.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

ae42b0bb-72df-4650-9d0d-48dd0306eea4

### Paper URL

https://arxiv.org/html/2404.14837v1?_immersive_translate_auto_translate=1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
