### ISSUE TITLE
 bibliography missing

### ISSUE THREAD

**Issue by ZhouLinli** [arXiv/html_feedback#1656]
### Description

it seems this report is not in your bibliography

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

2cb8a340-f85f-421c-be99-1db55b1b4907

### Paper URL

https://arxiv.org/html/2405.14007v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
