### ISSUE TITLE
 HI,  Thank you for a very good paper.

### ISSUE THREAD

**Issue by dongjineee** [arXiv/html_feedback#1669]
### Description

I really want to try this. Could you please share the code?or is there a reference to refer to?Thank you

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

2e020b98-42c6-496c-b55e-0fd6434eedc9

### Paper URL

https://arxiv.org/html/2403.01928v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
