### ISSUE TITLE
 Incorrect spelling

### ISSUE THREAD

**Issue by Ramyahkay** [arXiv/html_feedback#1698]
### Description

Change 'intruction-tunes' to 'instruction-tunes' in the third paragraph under Introduction section.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

7a141fed-eb76-4e65-8c99-d6921bf2c675

### Paper URL

https://arxiv.org/html/2407.02485v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
