### ISSUE TITLE
 Whether the parameter is incorrect

### ISSUE THREAD

**Issue by Jarvis9908** [arXiv/html_feedback#1783]
### Description

The seconde parameter: WH, whether the correct parameter is "HI"?

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

63294773-8165-494b-a317-0921917634bf

### Paper URL

https://arxiv.org/html/2403.11703v1

### Browser

Chrome/126.0.0.0

### Device Type

pc

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
