### ISSUE TITLE
a typing error

### ISSUE THREAD

**Issue by jong1-choi** [arXiv/html_feedback#1786]
### Description

velocities

### (Optional:) Please add any files, screenshots, or other information here.

2.1.4 Hybrid Methods: PIC and FLIP

4th paragraph

Once this new velocity field has been computed, the velocites are interpolated back to the particles. 

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

f6b7eb07-8811-4997-9d1a-d29255ebe91e

### Paper URL

https://arxiv.org/html/2404.01931v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
