### ISSUE TITLE
 Correlation or Covariance

### ISSUE THREAD

**Issue by MichelFaloughi** [arXiv/html_feedback#1792]
### Description

Hey, thanks for your tutorial! Was this meant to be covariance or correlation?
![Screenshot 2024-07-24 225048](https://github.com/user-attachments/assets/c6fdc8bc-fd3e-4093-ad12-ffc171eb0a1f)

### (Optional:) Please add any files, screenshots, or other information here.

[](url)

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

1eb0859f-37c8-411c-b9cd-be2e14d4c454

### Paper URL

https://arxiv.org/html/2009.10862v5

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
