### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by eraser333** [arXiv/html_feedback#1809]
### Description

2 NVIDIA A100 GPUs (each with 8o GB VRAM) 80GB VRAM

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

df7846d7-fa61-4f51-b929-d506b655f60c

### Paper URL

https://arxiv.org/html/2404.14294v3?_immersive_translate_auto_translate=1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
