### ISSUE TITLE
 The experimental HTML is not good-looking.

### ISSUE THREAD

**Issue by spring-wreath** [arXiv/html_feedback#1810]
### Description

The front size is too big and the style of the page is childish.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

057d7afe-9941-4f31-90eb-9a515d798a41

### Paper URL

https://arxiv.org/html/2401.03788v1

### Browser

Chrome/126.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
@spring-wreath first time I see "childish" as a design adjective, interesting!

Could you share if you have any browser zoom at all when browsing (I often use 150%) and enumerate a couple of the details you find most unpleasant? 

A screenshot or two would be a nice addition to this kind of report.
