### ISSUE TITLE
 in latex

### ISSUE THREAD

**Issue by dylanelliotttamu** [arXiv/html_feedback#1832]
### Description

in latex needs to be compiled with pdftex

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

96b89e96-2324-4bc7-9f5f-172d6859c4d1

### Paper URL

https://arxiv.org/html/2407.15586v1

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This repository only tracks the quality of the experimental HTML format. Thank you!
