### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by luc--** [arXiv/html_feedback#1860]
### Description

For this reference in this article <https://arxiv.org/html/2408.01663v1>

`Huang et al. [2022] H.-Y. Huang, M. Broughton, J. Cotler, S. Chen, J. Li, M. Mohseni, H. Neven, R. Babbush, R. Kueng, J. Preskill, and J. R. McClean, Science 376, 1182 (2022), https://www.science.org/doi/pdf/10.1126/science.abn7293
`
The url of science.com isn't right, it points to <https://arxiv.org/abs/https://www.science.org/doi/pdf/10.1126/science.abn7293>

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

af0489d9-b412-44fe-82f2-5fdade5cabb9

### Paper URL

https://arxiv.org/html/2408.01663v1

### Browser

Chrome/127.0.0.0

### Device Type

Windows 10

**Comment by dginev** [comment]
@luc-- this is also a problem in the PDF version of the article. 

It may be a good idea to contact the author and request a correction to their source.
