### ISSUE TITLE
 Links to codes are not working

### ISSUE THREAD

**Issue by btnorway** [arXiv/html_feedback#1861]
### Description

The links to the codes in this manuscript are not working. Codes are not available for download. Could the author check them again?

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

6efbe435-2c27-4198-add7-33a592a3599b

### Paper URL

https://arxiv.org/html/2408.01823v1

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
