### ISSUE TITLE
Minor issues with Eq.(12) and (13)

### ISSUE THREAD

**Issue by eash-d** [arXiv/html_feedback#1874]
### Description

Is this a "-" ? Based on the context, I think it is "=" ?Eq(12)(13)

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

c3ffdcff-fedc-4e5f-8958-81bbe32a2dc0

### Paper URL

https://arxiv.org/html/2307.06742v2

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by eash-d** [comment]
According their definition of $d_{p,k}$ and $x_{ij}^{pk}$ in  paper, Eq(12),(13) is a kind of "flow conservation".
That means, however what value of  $d_{pk}$ ,
$\sum {x_{j,fp}} = \sum {x_{fp,j}}$ this equal awalys holds
But if $d_{pk} = 1$, that means $\sum {x_{j,fp}} \ne \sum {x_{fp,j}}$, that's false.
$\sum {x_{j,fp}} = \sum {x_{fp,j}} = d_{pk}$ is true.

I'm not expert, if my understood is wrong, point it out, I will be very grateful!

**Comment by dginev** [comment]
@eash-d I see, thank you for explaining.

If your comment is about the actual scientific content of the article, please reach out directly to the authors. The issues in this repository track the generation of HTML versions of articles, as written. And authors generally do not read these issues.

**Comment by eash-d** [comment]
Ok, thank you for your reply
