### ISSUE TITLE
 studied case images 

### ISSUE THREAD

**Issue by chihyun-chang** [arXiv/html_feedback#1892]
### Description

Would be kind to use aesthetic images even it’s for training purposes. 🙏

### (Required) What is this issue most closely related to? Select one.

Figures

### Internal issue ID

0fe24c8c-16aa-481c-bc22-2ce7045b1b80

### Paper URL

https://arxiv.org/html/2405.18654v1

### Browser

Safari/604.1

### Device Type

n/a

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
