### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by alisaaalehi** [arXiv/html_feedback#1915]
### Description

Phrase "retinal optical" is repeated in ""retinal optical retinal optical coherence tomography (OCT)""

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

5654ba2e-263c-4ab5-89b0-8e58ca9c3959

### Paper URL

https://arxiv.org/html/2407.08410v1

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
@alisaaalehi this is also a problem in the PDF. You may want to contact the authors directly to ask for a correction.
