### ISSUE TITLE
 [feature request] allow comments on selected text

### ISSUE THREAD

**Issue by hjk41** [arXiv/html_feedback#1948]
### Description

It would be very interesting if we can comment on selected text in the papers. This would allow people to discuss specific topics. For example, we can point out typos and errors in papers, or discuss related works that are not cited by the paper.Although AlphXiv allows comment on SOME papers, it  only allows commenting on the whole paper, I think partly because they only render the papers in PDF, which makes it a bit hard to comment on selected paragraph, which should be easy with HTML.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

fdbd2fb7-af89-403e-be6b-abf4d507b2c1

### Paper URL

https://arxiv.org/html/2408.08921v1

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
It is probably most productive to track alphaXiv in the near term.
They started with using the HTML versions initially, but switched to PDF until overall fidelity improves. Which brings me to...

This repository only tracks the quality of the experimental HTML format, so general arXiv features are a bit out of scope. Thank you!
