### ISSUE TITLE
 Tails Tell Tales: Chapter-Wide Manga Transcriptions with Character Names

### ISSUE THREAD

**Issue by redvalley9877** [arXiv/html_feedback#1955]
### Description

I think this content is very interested and probably useful, but I should show concerned that script Artificial Intelligence(script AI)has not any ethics for intelligent property and some individuals rights. Then if someone will use this AI intentionally and illegally, we have no available to control indeed.Above then in this content, I guess, no permitted contents is included already.This is nonsense .

### (Optional:) Please add any files, screenshots, or other information here.

[Extracted 2408.00298v1 (1).pdf](https://github.com/user-attachments/files/16699052/Extracted.2408.00298v1.1.pdf)

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

5de63295-da0c-49e0-97c0-7f7c0bcd0c50

### Paper URL

https://arxiv.org/html/2408.00298v1

### Browser

Safari/604.1

### Device Type

iOS

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
