### ISSUE TITLE
 Ranking of Volatility 

### ISSUE THREAD

**Issue by RetireeRoy** [arXiv/html_feedback#1971]
### Description

On third paragraph under '5. Signature Plot', article ranked volatility as follows:FGBX, FGBM, FGBL and FGBS.In the writing that follows it suggested FGBL is more volatile than FGBM. The correct ranking it seems should instead be FGBX *FGBL *FGBM FGBS...or is it?

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

b5404f4d-3fc8-4cd9-b8b9-f304beb08b64

### Paper URL

https://arxiv.org/html/2401.10722v1

### Browser

Chrome/127.0.0.0

### Device Type

Android

**Comment by dginev** [comment]
Please contact the authors directly for questions on document content.

This repository only tracks the quality of the experimental HTML format. Thank you!
