### ISSUE TITLE
Ar5iv Bug Report

### ISSUE THREAD

**Issue by YiChen8185** [arXiv/html_feedback#2]
# Bug Reprot 
 
 ## Description 

Description of issue:

Please attach a screenshot(or document) if possible.

  Steps to reproduce:

  1. Go to the chat interface.
  2. Type 'Hello' and press Enter.
  3. Observe the error message.

  Expected result: The system should respond with a greeting.

  Actual result: An error message is displayed.
---
  ## Auto Fill Data 

**article_url**: https://ar5iv.labs.arxiv.org/html/1808.08002

**reportTime**: Tue Jun 27 2023 16:20:02 GMT-0400 (Eastern Daylight Time)

**browserInfo**: Chrome/114.0.0.0

**description**: hello world

**conversion_report**: https://ar5iv.labs.arxiv.org/log/1808.08002

**source_file**: https://arxiv.org/abs/1808.08002

htmlText: undefined

location_low: undefined

location_high: undefined

initiationWay: button

**Comment by cbf66** [comment]
"Bug Reprot" -- what's a "Reprot"?

Please coordinate with @mnazzaro about using a github app for this.
