### ISSUE TITLE
 Incorrect Example

### ISSUE THREAD

**Issue by Lukas-wsc** [arXiv/html_feedback#2004]
### Description

Elvis Presley also had a father that was an actor which means that this example doesn't make sense. His father is Venon Presley who for example played the role of himself in Elvis on Tour.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

b2a21441-1627-4a00-b10c-484307fc44de

### Paper URL

https://arxiv.org/html/2303.08774v6

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly on questions regarding document content.

This repository only tracks issues with the experimental HTML format.
