### ISSUE TITLE
 liver

### ISSUE THREAD

**Issue by PavelHakobyan** [arXiv/html_feedback#2019]
### Description

some drugs and systems affected the liver and developed fever 

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

1ca4442e-82b6-42b1-9100-d2a8fa2347e7

### Paper URL

https://arxiv.org/html/2401.05654v1

### Browser

Chrome/128.0.0.0

### Device Type

Android

**Comment by dginev** [comment]
Please contact the authors directly for feedback on the document content.

This repository only tracks reports on the quality of the experimental HTML format.
