### ISSUE TITLE
 typo

### ISSUE THREAD

**Issue by Garrett-R16** [arXiv/html_feedback#2055]
### Description

typo

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

801b5762-90ac-4144-a033-7e4d43f2209e

### Paper URL

https://arxiv.org/html/2401.04212v1

### Browser

Chrome/128.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for feedback on the document content.

This repository only tracks reports on the quality of the experimental HTML format.
