### ISSUE TITLE
 the number of top-kaux

### ISSUE THREAD

**Issue by Lydiatingting** [arXiv/html_feedback#2058]
### Description

why the number of top-kaux of GPT2-small in the paper is 512 but in the code is 256?

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

087954a0-acd2-4ebd-9c99-0fd8017a223c

### Paper URL

https://arxiv.org/html/2406.04093v1

### Browser

Chrome/128.0.0.0

### Device Type

cuda

**Comment by dginev** [comment]
Please contact the authors directly for feedback on the document content.

This repository only tracks reports on the quality of the experimental HTML format.
