### ISSUE TITLE
 翻译意思相反

### ISSUE THREAD

**Issue by CodingPerNight** [arXiv/html_feedback#2070]
### Description

the one-to-many branch provides much richer supervisory signals than one-to-one branch。翻译成 一对一分支提供的监督信号比一对多分支丰富得多

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

8e3fdebd-3877-4b2c-af75-155443d4aab5

### Paper URL

https://arxiv.org/html/2405.14458?_immersive_translate_auto_translate=1

### Browser

Chrome/128.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for feedback on the document content.

This repository only collects reports on the experimental HTML format.
