### ISSUE TITLE
 The Dirac Equation Near Centenary: a Contemporary Introduction to the Dirac Equation Consideration

### ISSUE THREAD

**Issue by vsimulik** [arXiv/html_feedback#2080]
### Description

More then 35 approaches to the Dirac equation derivation are presented. The various physical principles and mathematical methods are used. A review of well-known and not enough known contributions to the problem is given, the unexpected and unconventional derivations are presented as well. Three original approaches to the problem suggested by the author are considered as well. They are (i) the generalization of H. Sallhofer derivation, (ii) the obtaining of the massless Dirac equation from the M

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

24b1dbc7-0fad-455a-8f95-1b16edeed397

### Paper URL

https://services.arxiv.org/html/submission/5847248/view

### Browser

Firefox/115.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for feedback on the document content.

This repository only tracks reports on the quality of the experimental HTML format.
