### ISSUE TITLE
 Version 2 has been updated for this paper on arXiv

### ISSUE THREAD

**Issue by XiCheng129** [arXiv/html_feedback#2138]
### Description

The author has updated version 2 of this paper in August on arXiv. Please update the version. Thank you.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

a3d41065-92b2-4681-bb1c-24bf8db6e01a

### Paper URL

https://arxiv.org/html/2405.08298v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by dginev** [comment]
@XiCheng129 the updated v2 is now available:

https://arxiv.org/html/2405.08298v2
