### ISSUE TITLE
 Connecting with Zotero

### ISSUE THREAD

**Issue by lynn-1998** [arXiv/html_feedback#2154]
### Description

Unable to download PDF manuscripts (for all) using Zotero plugin in Windows operating systems 

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

7c9de622-d137-47b3-8813-52df09c0d209

### Paper URL

https://arxiv.org/html/2409.11654v1

### Browser

Chrome/128.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This may be off-topic for this repository, which tracks issues with the experimental HTML format.

You may want to contact the Zotero team (or use a PDF link, instead of an HTML link?)
