### ISSUE TITLE
 GPU0 looks like GPUo

### ISSUE THREAD

**Issue by Eugene29** [arXiv/html_feedback#2180]
### Description

Title.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

1e75649d-f516-4d19-befa-4627485e676a

### Paper URL

https://arxiv.org/html/2405.07719v3

### Browser

Chrome/129.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for the report. We have migrated to `rival-sans` which avoids this problem.

**Comment by Eugene29** [comment]
Cool cool, looking forward to more html arxiv papers!
