### ISSUE TITLE
 incomplete sentence

### ISSUE THREAD

**Issue by BobBranson** [arXiv/html_feedback#2182]
### Description

incomplete sentence here

### (Optional:) Please add any files, screenshots, or other information here.

![image](https://github.com/user-attachments/assets/7fe221db-5fcf-4215-9bc2-2a9af3adcbe2)

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

f397c61f-c82c-4916-a4b0-da4cad0294f5

### Paper URL

https://arxiv.org/html/2408.08921v2

### Browser

Chrome/129.0.0.0

### Device Type

computer

**Comment by dginev** [comment]
@BobBranson surprisingly, this is also a problem in the PDF - so I assume it's an oversight with the actual content of the document.

Could you contact the authors directly and ask for a correction? 

This repository tracks issues with the experimental HTML format, without an expectation of author involvement.
