### ISSUE TITLE
 Update Version 2

### ISSUE THREAD

**Issue by XiCheng129** [arXiv/html_feedback#2189]
### Description

This paper has been updated with version on arXiv. Thank you very much.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

78b6ca61-cb73-4040-ad0f-a1e450bb8ee2

### Paper URL

https://arxiv.org/html/2405.08306v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by dginev** [comment]
Yes, v2 HTML appears to be available:

https://arxiv.org/html/2405.08306v2
