### ISSUE TITLE
Reference links 2 and 3 are reversed

### ISSUE THREAD

**Issue by lrobert69** [arXiv/html_feedback#2238]
### Description

The URL 2 is for ressource 3, and URL 3 is for 2.

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

bec91d12-320d-4813-887a-9a7430539359

### Paper URL

https://arxiv.org/html/2409.12676v1

### Browser

Chrome/129.0.0.0

### Device Type

Android

**Comment by dginev** [comment]
Hi @lrobert69 could you show one example URL where this is the case? 

Also, is this the same as in the PDF? If the mistake is in the article's source, you should contact the authors for a correction.
This space only tracks issues with the HTML format of the article.

**Comment by lrobert69** [comment]
You are right, it's a simple error in the content, an inversion in the
references at the bottom of the article. So it's not really important.

Le ven. 4 oct. 2024 à 17:47, Deyan Ginev ***@***.***> a
écrit :
