### ISSUE TITLE
 minor change

### ISSUE THREAD

**Issue by dlwlrmaIU0516** [arXiv/html_feedback#2269]
### Description

e.g., -> e.i.,

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

0ac62834-ea92-4e55-86ae-d30a6de047e4

### Paper URL

https://arxiv.org/html/2312.14303v2/

### Browser

Chrome/129.0.0.0

### Device Type

?

**Comment by dginev** [comment]
Please contact the authors directly for editorial changes. This repository only tracks quality control of the experimental HTML format.
