### ISSUE TITLE
 该文章已撤稿，请把该文章网页下架

### ISSUE THREAD

**Issue by makeit1012** [arXiv/html_feedback#2307]
### Description

您好，该篇文章已经于2024年三月份撤稿，请将该网页下架，目前已经影响到我的查重

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

c9166f72-3983-4dde-8f7f-b92e213172fb

### Paper URL

https://arxiv.org/html/2401.10519v1

### Browser

Chrome/128.0.0.0

### Device Type

Android

**Comment by dginev** [comment]
Only v2 of this article has been withdrawn. v1 is still available, so this is as intended.
