### ISSUE TITLE
 This article has been withdrawn. Please delete this page.

### ISSUE THREAD

**Issue by makeit1012** [arXiv/html_feedback#2308]
### Description

This article has been withdrawn at 2024 /3 / 22 09:09:45 UTC (1 KB). Please delete this page. This page influenced my article to be republished

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

691882ff-a4db-4e8b-971c-ffa79c2c553a

### Paper URL

https://arxiv.org/html/2401.10519v1

### Browser

Chrome/128.0.0.0

### Device Type

Android

**Comment by dginev** [comment]
Only `v2` of this article has been withdrawn. The first version is still available on arXiv, so this is as intended.
