### ISSUE TITLE
 Zotero not working for retrieval

### ISSUE THREAD

**Issue by Presence76** [arXiv/html_feedback#2313]
### Description

same as title

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

9d6f97cf-cb1f-4482-8daf-68e5d91deee9

### Paper URL

https://arxiv.org/html/2402.14848v1

### Browser

Firefox/131.0

### Device Type

windows 11 AMD cpu and gpu

**Comment by dginev** [comment]
Please report this to the Zotero team.
