### ISSUE TITLE
 This article has been withdrawn. Please delete this page.

### ISSUE THREAD

**Issue by makeit1012** [arXiv/html_feedback#2321]
### Description

This article has been withdrawn at 2024 /3 / 22 09:09:45 UTC (1 KB). Please delete this page. This page influenced my article to be republished

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

9ce6541d-14fd-4739-8fa5-0e20767913b2

### Paper URL

https://arxiv.org/html/2401.10519v1

### Browser

Chrome/129.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Only `v2` of the article has been withdrawn. Version one is still on arXiv, so this is as intended.

**Comment by makeit1012** [comment]
sorry，it's my fault. I will withdraw  soon.



---- Replied Message ----
| From | Deyan ***@***.***> |
| Date | 10/15/2024 06:30 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [arXiv/html_feedback] This article has been withdrawn. Please delete this page. (Issue #2321) |

Only v2 of the article has been withdrawn. Version one is still on arXiv, so this is as intended.
