### ISSUE TITLE
 Missing comma 

### ISSUE THREAD

**Issue by guilherme-butzke** [arXiv/html_feedback#2328]
### Description

Missing comma in text

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

09557184-ebcb-4138-9ba0-82dfdb705a0f

### Paper URL

https://arxiv.org/html/2312.10997v5

### Browser

Chrome/129.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly for content corrections.
