### ISSUE TITLE
 中文论文中Abstract标题的翻译问题

### ISSUE THREAD

**Issue by jevliu** [arXiv/html_feedback#2355]
### Description

应该翻译为 摘要

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

3f8e4274-4d28-464b-a4df-6ba6c86e5e3c

### Paper URL

https://arxiv.org/html/2405.18614?monicaAutoTranslate=1

### Browser

Chrome/129.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the team of the translation tool directly, arXiv does not currently prepare translations for its articles.
