### ISSUE TITLE
 can't download

### ISSUE THREAD

**Issue by sftsgly** [arXiv/html_feedback#2357]
### Description

can't open pdf

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

3006b1a1-3c3b-4210-a998-38022d6c47e2

### Paper URL

https://arxiv.org/html/2312.06573v1

### Browser

Chrome/128.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This may have been due to the high server load during this week, please try again.
