### ISSUE TITLE
 Incorrect number of parameters

### ISSUE THREAD

**Issue by Nacriema** [arXiv/html_feedback#2362]
### Description

Should be 2885888 instead of 28858888

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

51e66bea-5853-49d9-9ba7-13451d13da93

### Paper URL

https://arxiv.org/html/2407.21308v2

### Browser

Chrome/127.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors directly with content corrections, this repository only tracks the quality of the experimental HTML format.
