### ISSUE TITLE
 must be a formatting issue

### ISSUE THREAD

**Issue by tedstrazimiri** [arXiv/html_feedback#2390]
### Description

Converlutional?Meural?Metworks?

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

98df9b40-f0ed-4ec5-9d11-51853dccbfa8

### Paper URL

https://arxiv.org/html/2401.00442v1/

### Browser

Chrome/129.0.0.0

### Device Type

pc

**Comment by dginev** [comment]
Please contact the authors directly for content feedback - the report matches the PDF of the article.

This repository only tracks reports on the quality of the experimental HTML support.
