### ISSUE TITLE
 URL linebreak

### ISSUE THREAD

**Issue by kesslerr** [arXiv/html_feedback#2414]
### Description

link is line-broken, which obscures the actual URL

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

32c0eae2-9560-4ea0-813c-04cccdd6e22e

### Paper URL

https://arxiv.org/html/2410.14453v1

### Browser

Safari/605.1.15

### Device Type

arxiv

**Comment by dginev** [comment]
@kesslerr this may be a feature, unsure. The trade-off is that if URLs were never line-broken we would induce more situations where the justified text layout has whitespace gaps.

It is worth experimenting with it disabled I suppose, but to my line-breaking is almost always a feature in a web context (assuming the line width is as expected).
