### ISSUE TITLE
 Franka kitchen images are blur

### ISSUE THREAD

**Issue by keivalya** [arXiv/html_feedback#2445]
### Description

The images in the section 5.2 Standard Franka Kitchen Environment are blur. Please replace them with good quality pictures.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

859c06d0-ecb7-43ab-9269-98913f8407c0

### Paper URL

https://arxiv.org/html/2408.08441v1

### Browser

Chrome/129.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
This is consistent with the PDF, and with the author comment of 64x64 size. 

Please reach out to the authors for content corrections, this repository only tracks quality issues for the HTML format.
