### ISSUE TITLE
 related work

### ISSUE THREAD

**Issue by Hyp26cs** [arXiv/html_feedback#2472]
### Description

In the paragraph 2 of section 2.2, there exists two duplicate “For example”.

### (Optional:) Please add any files, screenshots, or other information here.

![Uploading 12661730199079_.pic.jpg…]()

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

6d020193-6e66-4ecf-9633-cda907c22cfb

### Paper URL

https://arxiv.org/html/2409.20012

### Browser

Chrome/130.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Hi @Hyp26cs this appears also in the PDF and is likely a typo in the article source. Please reach to authors directly for content corrections - this repository only tracks issues with the experimental HTML format.
