### ISSUE TITLE
 https://arxiv.org/html/2410.19729v1

### ISSUE THREAD

**Issue by Doliometer** [arXiv/html_feedback#2478]
### Description

Forgive me but I think the year given between authors and abstract in HTML differs from the year given above the title, 2022 vs 2024.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

a2be520b-76bf-4688-b88d-608b36403724

### Paper URL

https://arxiv.org/html/2410.19729v1

### Browser

Firefox/115.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for the report. This appears to be an oversight in the submission and needs a correction by the authors - same behavior in PDF and HTML. 

Please let the authors know directly, as this repository only tracks issues with the experimental HTML format.
