### ISSUE TITLE
 Should be harmonic not ahrmonic

### ISSUE THREAD

**Issue by matthew-boyens** [arXiv/html_feedback#2483]
### Description

Spelling mistake

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

c776a2e1-44bc-4196-a9b7-1d9a0a5a57eb

### Paper URL

https://arxiv.org/html/2405.03770v1

### Browser

Chrome/129.0.0.0

### Device Type

Web

**Comment by dginev** [comment]
Thank you for the report. Please contact the document authors directly for content corrections, as it is also the case in the PDF file.

This repository only tracks reports on the experimental HTML format.
