### ISSUE TITLE
 Fourier PINNs: From Strong Boundary Conditions to Adaptive Fourier Bases

### ISSUE THREAD

**Issue by 123zeo123** [arXiv/html_feedback#2589]
### Description

Interest is rising in Physics-Informed Neural Networks (PINNs) as a mesh-free alternative to traditional numerical solvers for partial differential equations (PDEs). However, PINNs often struggle to learn high-frequency and multi-scale target solutions. To tackle this problem, we first study a strong Boundary Condition (BC) version of PINNs for Dirichlet BCs and observe a consistent decline in relative error compared to the standard PINNs. We then perform a theoretical analysis based on the Four

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

449bdd38-f3a5-4ea8-a721-e8c5fc69b78c

### Paper URL

https://arxiv.org/html/2410.03496v1

### Browser

Firefox/132.0

### Device Type

Desktop

**Comment by Guoqimg** [comment]
Hello, may I ask if there are any relevant codes for this article?
