### ISSUE TITLE
 Remove this paper.

### ISSUE THREAD

**Issue by Mukul111840** [arXiv/html_feedback#2592]
### Description

Please remove this paper from arXiv as there is some unclear and incorrect estimates.

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

e86f0a33-4a88-4220-8e6a-d2466c1b1807

### Paper URL

https://arxiv.org/html/2405.08360v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for the report. Please contact the document authors directly for content corrections.

This repository only tracks reports on the experimental HTML format.
