### ISSUE TITLE
 Errata

### ISSUE THREAD

**Issue by dmolina** [arXiv/html_feedback#2605]
### Description

"Iterative Generaiton"  should be "Iterative Generation"

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

95570007-93cc-4b57-8d28-b5ee7ae083e0

### Paper URL

https://arxiv.org/html/2401.10034v3

### Browser

Firefox/131.0

### Device Type

Desktop

**Comment by dginev** [comment]
This report matches the PDF. 

Please contact the authors directly for content corrections to the article, this repository only tracks issues with the HTML format.
