### ISSUE TITLE
 There is no link for the replication package

### ISSUE THREAD

**Issue by AltafAllahAbbassi** [arXiv/html_feedback#2608]
### Description

the link for the replication package is not working 

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

078808ab-2d53-4d1d-83b7-b19ecb249f77

### Paper URL

https://arxiv.org/html/2310.02059v2

### Browser

Chrome/123.0.0.0

### Device Type

computer

**Comment by dginev** [comment]
Thank you for the report. Please contact the document authors directly for content corrections, as it is also the case in the PDF file.

This repository only tracks reports on the experimental HTML format.
