### ISSUE TITLE
 Zotero-Web-Clipper (might also impcat other citation software)

### ISSUE THREAD

**Issue by MarioMuehlematter** [arXiv/html_feedback#2636]
### Description

the weblipper is no longer able to recognize the right doi/ title authors. this makes the htmml version less useful

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

ca88244f-e73a-4a9a-b96c-09996cffad5e

### Paper URL

https://arxiv.org/html/2410.03131v1

### Browser

Firefox/132.0

### Device Type

Desktop

**Comment by dginev** [comment]
@MarioMuehlematter could you report this to Zotero directly? We would like to know if there are issues in the HTML that cause problems, but this report is not specific enough yet.

**Comment by MarioMuehlematter** [comment]
Reported it to the zotero forum.
