### ISSUE TITLE
 The HTML version is not updated on google.

### ISSUE THREAD

**Issue by Ash1362** [arXiv/html_feedback#2662]
### Description

Is it possible that this version (the last update) is shown on google search?

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

46abb398-618f-409b-9f53-7de5a502f77a

### Paper URL

https://arxiv.org/html/2212.04466v12

### Browser

Chrome/131.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
I think that is upto google, apologies. The latest version is available to be indexed.

Out of scope for the repository here, which tracks issues with the HTML format itself.

**Comment by Ash1362** [comment]
Thank you for your fast response. You're absolutely right. I must wait for few days to see if google browser will be updated. It's a bit confusing for readers and annoying for authors when google (and researchgate) suggest different versions of the same article, but this is absolutely not upto your team.
Kind regards,Ashkan


    On Friday, November 22, 2024 at 08:05:27 PM GMT, Deyan Ginev ***@***.***> wrote:  
 
 


Closed #2662 as completed.
