### ISSUE TITLE
Can I contribute to the development of the arxiv html version?

### ISSUE THREAD

**Issue by 312shan** [arXiv/html_feedback#2688]
### Description

Can I contribute to the development of the arxiv html version?
Is this open source? I think this feature is valuable

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

null

### Paper URL

null

### Browser

null

### Device Type

mac pro, chrome

**Comment by dginev** [comment]
@312shan thank you for the interest!

The current live HTML project is indeed open source, you can find it [here](https://github.com/arxiv/arxiv-view-as-html).

I wouldn't advise you to contribute to that directly today, as I am in the process of rearranging some of the infrastructure pieces, so contributions may not get directly applied in a timely manner.

What I would instead encourage you to do is to consider helping to improve the underlying conversion to HTML, which is an active ongoing project called [latexml](https://github.com/brucemiller/LaTeXML/), released in the Public Domain. 

I am myself working on ensuring that arXiv has a streamlined path to quickly turn LaTeXML improvements into improvements to arXiv's live HTML pages, and will get back to proper LaTeXML development soon after.
