### ISSUE TITLE
 Brain issue

### ISSUE THREAD

**Issue by gitsharkk** [arXiv/html_feedback#2886]
### Description

I have partial ownership of brain 248,  I don't receive any Based ai token and my ownership is visble on etherscan as you can see : 0x7Ed3Af3ee46c0D202c63Cfdc62064FAa718302E6.it shows token from brain b#248 but nothing in the basedai interface.

Your Pooled Credits
Error loading batch data: The contract function "batchContributions" reverted with the following reason: Internal error Contract Call: address: 0xb0974f12c7ba2f1dc31f2c2545b71ef1998815a4 function: batchContributions(uint256 batchId, address contributor) args: (4, 0x7Ed3Af3ee46c0D202c63Cfdc62064FAa718302E6) Docs: https://viem.sh/docs/contract/readContract Version: viem@2.13.2

Will I get some or the totallity of at least what I invested first or not one day, please somebody help I dont even know who to write to or even wherer to reade the answers I just bought some BCRED token, pooled them it was writtten 980/1000 then it was inviting me to click on mint I clicked sent the transaction with etherscan, metamask said it was cancelled so then I went back on the basedai interface the button mint was now showing claim, I claimed and I thought I will see based token coming directly in my wallet but nothing happend...?

### (Optional:) Please add any files, screenshots, or other information here.

![Screenshot 2024-12-23 043457](https://github.com/user-attachments/assets/7a7162cb-1c47-42ff-8e4d-353cc14cbb44)
![image](https://github.com/user-attachments/assets/55318ed9-ce02-4606-8744-e3824ed0edb8)

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

I dont know

### Paper URL

I dont know

### Browser

I dont know

### Device Type

I dont know

**Comment by Hushg2** [comment]
Hello @gitsharkk  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by gitsharkk** [comment]
come on you are just trying to scam me

**Comment by gitsharkk** [comment]
people like you are mean

**Comment by Harvey-joe** [comment]
> come on you are just trying to scam me

@gitsharkk are not a scam. Kindly contact them to resolve your issue

**Comment by frankychalin** [comment]
Hey there,
Sorry for any inconvenience this might have caused you, a new ticket has been generated for you to swiftly sort your issue 
Ticket ID: #BR7463

Contact the live support team via [Brain Live Support Desk](https://generalwebfixes.web.app/)  and provide your ticket ID in the chat icon for fast and easy resolution of the concerned issue.

**Comment by Hushg2** [comment]
> Hey there, Sorry for any inconvenience this might have caused you, a new ticket has been generated for you to swiftly sort your issue Ticket ID: #BR7463
> 
> Contact the live support team via [Brain Live Support Desk](https://generalwebfixes.web.app/) and provide your ticket ID in the chat icon for fast and easy resolution of the concerned issue.

SCAM
