### ISSUE TITLE
2306.16433v1:65227659-9ca8-4edd-aa51-34bd3637d772 - The long alphanumeric auto subject line isnt very useful, it seems

### ISSUE THREAD

**Issue by SBBCornell** [arXiv/html_feedback#3]
### Description
 Testing a bug report. This is Shamsi.

**Comment by chrisjcameron** [comment]
Hopefully, we can move that identifier to the body! The long alphanumeric is supposed to help us link this report to the internal data we capture so we can attach extra detail to the bug report.
