### ISSUE TITLE
 broken links in the paper

### ISSUE THREAD

**Issue by jessiethw** [arXiv/html_feedback#371]
### Description

Links to sections, figures, and references are broken in the html version and result in a 404 error when clicked. Links in the table of contents on the left hand side of the page are also broken.

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

2a6949a4-7dc2-4f11-acc6-2fbebb6cd30c

### Paper URL

https://arxiv.org/html/2401.06666v1

### Browser

Firefox/122.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Hello @jessiethw, we have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. Thanks for your report.

**Comment by chrisjcameron** [comment]
Hello @jessiethw, this paper has been rebuilt with the updated converter and appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
