### ISSUE TITLE
Section links in left Navigation bar are dead

### ISSUE THREAD

**Issue by jetlime** [arXiv/html_feedback#378]
### Description

When clicking on the link of any section on the left navigation bar, the page returns a dead link with a 400 http error.

### (Optional:) Please add any files, screenshots, or other information here.

To reproduce the error, click on a any section link on the left navigation bar of the affected page,

![image](https://github.com/arXiv/html_feedback/assets/29337128/79e1ad82-bfc1-48ca-bd71-9993422d523d)

For any section, the  link returns a dead page, returning a 404 error.

![image](https://github.com/arXiv/html_feedback/assets/29337128/dda3081c-f894-4b1f-9e69-94dad3648466)

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

6c28d2fe-438f-4012-abd9-dbab8ec8622e

### Paper URL

https://arxiv.org/html/2401.08406v2

### Browser

Firefox/122.0

### Device Type

Desktop

**Comment by veinamond** [comment]
It is fixed by removing "/" character.
E.g. https://arxiv.org/html/2401.05268v2/#bib.bib49 ->https://arxiv.org/html/2401.05268v2#bib.bib49

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
