### ISSUE TITLE
 The reference will be redirected to 404

### ISSUE THREAD

**Issue by Cieeiee** [arXiv/html_feedback#382]
### Description

The reference URL `https://arxiv.org/html/2401.05268v2/#bib.bib49` is 404.

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

dde3729e-a769-409b-9e31-0f3aedbb2db3

### Paper URL

https://arxiv.org/html/2401.05268v2

### Browser

Chrome/120.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
