### ISSUE TITLE
 Links to references return 404

### ISSUE THREAD

**Issue by EdoardoPona** [arXiv/html_feedback#403]
### Description

opening links from references leads to a 404 arXiv page

### (Optional:) Please add any files, screenshots, or other information here.

For example, clicking on the highlighted link
<img width="1232" alt="Screenshot 2024-02-05 at 16 23 20" src="https://github.com/arXiv/html_feedback/assets/29152472/4b00a3ed-6453-4d43-9cdb-f838a9c20c3a">

leads to the following page. This occurs for all such links, generated for the references. 

<img width="1244" alt="Screenshot 2024-02-05 at 16 22 52" src="https://github.com/arXiv/html_feedback/assets/29152472/5e4d5951-89d7-4ad7-b824-b5f879ebeb11">

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

54cd3b31-38bd-41a0-9bb5-0d581b92e145

### Paper URL

https://arxiv.org/html/2401.06751v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
