### ISSUE TITLE
 References to Figures and Tables Not Found (404)

### ISSUE THREAD

**Issue by borjansz** [arXiv/html_feedback#407]
### Description

Whenever I try to follow a reference (link) to a figure or table in the paper, also links to other works, I get a 404 Not Found Error.

### (Optional:) Please add any files, screenshots, or other information here.

<img width="960" alt="image" src="https://github.com/arXiv/html_feedback/assets/92105060/5bfe4d53-5227-4c37-a084-95b7efb468f2">

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

eed839c4-e953-450b-9fef-cf38de62b295

### Paper URL

https://arxiv.org/html/2401.10185v1

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
