### ISSUE TITLE
 Citation references don't work

### ISSUE THREAD

**Issue by ignaloidas** [arXiv/html_feedback#452]
### Description

On https://arxiv.org/html/2401.07429v1 citation references link to a 404, instead of citations section as expected

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

79371df8-cde3-461a-a3e2-2e998870b00b

### Paper URL

https://arxiv.org/html/2401.07429v1

### Browser

Firefox/122.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
