### ISSUE TITLE
 Hyperlink in the table of contents doesn't work

### ISSUE THREAD

**Issue by asvin-kumar** [arXiv/html_feedback#461]
### Description

It goes to a 404 page that says broken URL. I couldn't highlight the table of contents on the left edge of the page so I'm highlighting the title. 

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

bdd913b2-fd6b-4361-9278-1b1cba1983b9

### Paper URL

https://arxiv.org/html/2304.08485v2

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
