### ISSUE TITLE
 bibliography / reference links go to 404 page

### ISSUE THREAD

**Issue by DarkOakSoftware** [arXiv/html_feedback#462]
### Description

All references to other research end up at a 404 page, instead of showing the bibliography information.

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

6b9b78dd-80ff-4f0e-8e07-4ed137427965

### Paper URL

https://arxiv.org/html/2401.10891v1

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
