### ISSUE TITLE
 some maths not rendered

### ISSUE THREAD

**Issue by chanokin** [arXiv/html_feedback#471]
### Description

I can see {propositionE} and {proofE} on a [paper](https://arxiv.org/html/2402.06121v1) instead of something properly rendered. Seems like algorithm rendering is also an issue.

### (Optional:) Please add any files, screenshots, or other information here.

![wrong_render](https://github.com/arXiv/html_feedback/assets/1545983/dccc56b2-bd68-4ed9-b84e-47cbbebc1fd0)

![wrong_algo_render](https://github.com/arXiv/html_feedback/assets/1545983/c4f6f545-2caa-4b31-98a4-3794f7dc2695)

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

93628758-f315-4405-91e6-31b7f419a952

### Paper URL

https://arxiv.org/html/2402.06121v1

### Browser

Firefox/122.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Hello @chanokin. Are any of the issues in your report not related to the `algseudocodex` or `proof-at-the-end` packages?

> HTML conversions [sometimes display errors](https://info.dev.arxiv.org/about/accessibility_html_error_messages.html) due to content that did not convert correctly from the source. This paper uses the following packages that are not yet supported by the HTML conversion tool. Feedback on these issues are not necessary; they are known and are being worked on.
> failed: algpseudocodex
> failed: proof-at-the-end

**Comment by chanokin** [comment]
Hi, I'm sorry, I think I shouldn't have jumped the gun on this one. I does have to do with the algo and proofs rendering.
