### ISSUE TITLE
 The links for the sections don't work!

### ISSUE THREAD

**Issue by facundoq** [arXiv/html_feedback#476]
### Description

They throw a 404

### (Required) What is this issue most closely related to? Select one.

Formula

### Internal issue ID

2beaab44-060a-4408-8713-caf49732914c

### Paper URL

https://browse.arxiv.org/html/2312.16864v1

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the html for this paper with the updated converter and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.

**Comment by facundoq** [comment]
Thanks, links working now!
