### ISSUE TITLE
 How to disable the HTML option

### ISSUE THREAD

**Issue by zhouyuqisconvex** [arXiv/html_feedback#486]
### Description

Is there a way to disable the HTML access for the paper, thanks.

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

386a2404-8911-4817-8156-9226479f9ba4

### Paper URL

https://arxiv.org/html/2402.04444v1

### Browser

Chrome/119.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Hi @zhouyuqisconvex. There is not a way to disable the HTML auto-conversion. Please submit feedback reports to help us improve the HTML conversion.
