### ISSUE TITLE
 The citation links are all broken

### ISSUE THREAD

**Issue by timmytonga** [arXiv/html_feedback#503]
### Description

The links for citations all lead to 404 errors urls. I think a hover over to display the full title, authors, and dates with clicking opening the link in new tab would be ideal.

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

fdba92b2-c82e-4c8c-b95e-4e15b47ae331

### Paper URL

https://arxiv.org/html/2401.11324v1

### Browser

Firefox/122.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
