### ISSUE TITLE
 PDF version not updated 

### ISSUE THREAD

**Issue by xialigang** [arXiv/html_feedback#505]
### Description

Hi arXiv admin,  I find that HTML is using the latest version, which is very good. But the PDF version, i.e. https://arxiv.org/pdf/2101.06944.pdf, is not the latest. Could you please fix it? Thanks!Best,Ligang

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

754edc5a-8ccd-48e4-a214-9cac5579a955

### Paper URL

https://arxiv.org/html/2101.06944v7

### Browser

Firefox/115.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Hi @xialigang, it looks like the PDF links are now pointing to https://arxiv.org/pdf/2101.06944v7.pdf (and the watermark shows v7). If you still see the older version, it may be a caching issue (either on your computer or the CDN service). Can you test it again tomorrow and see if the problem persists?
