### ISSUE TITLE
 Hyperlinks don't work 

### ISSUE THREAD

**Issue by tylerjhughes** [arXiv/html_feedback#507]
### Description

The hyperlinks in the contents section take me to a 404 error page.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

b1f05f8f-28b3-4b1c-826f-5fd624825857

### Paper URL

https://arxiv.org/html/2401.04165v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
