### ISSUE TITLE
 Clicking Table/Figure/Citation references in text leads to 404

### ISSUE THREAD

**Issue by zenineasa** [arXiv/html_feedback#520]
### Description

There are references to tables, figures or other cited papers within paragraphs. When I click on them, it takes me to a 404 page.

Potetial cause of the issue:
The reference links have an addition "/" at the end before refering to the identifier of the div. For example, the link points towards the following URL:
https://arxiv.org/html/2401.11338v2/#S3.F3
while it should have instead pointed towards the following URL:
https://arxiv.org/html/2401.11338v2#S3.F3

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

faef2bce-0b4e-41aa-b289-c26c03d6eca2

### Paper URL

https://arxiv.org/html/2401.11338v2

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
