### ISSUE TITLE
Bib Links Do Not Work

### ISSUE THREAD

**Issue by Sefank** [arXiv/html_feedback#527]
### Description

Every link in the text refers to a URL with an extra "/", like "https://arxiv.org/html/2401.10166v1/#bib.bib10". The correct URL should be "https://arxiv.org/html/2401.10166v1#bib.bib10".

### (Required) What is this issue most closely related to? Select one.

References

### Internal issue ID

7e2a7ecd-4f87-4a5e-bc81-657246a0b4c3

### Paper URL

https://arxiv.org/html/2401.10166v1

### Browser

Chrome/121.0.0.0

### Device Type

PC

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
