### ISSUE TITLE
 Name of the system: Trazine (possible correction)!

### ISSUE THREAD

**Issue by ssappati89** [arXiv/html_feedback#538]
### Description

Is it Triazine?

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

503a82f5-4a56-4f1e-b24d-16399a60234b

### Paper URL

https://arxiv.org/html/2402.13059v1

### Browser

Safari/605.1.15

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Can you help me understand this issue report? Is this an issue with the HTML rendering or the paper content itself. If this is related to paper content (that also appears in the PDF), then please reach out to the author.

**Comment by dginev** [comment]
I suspect this question should be taken to the document authors. Thanks!
