### ISSUE TITLE
 Illustration number display exception

### ISSUE THREAD

**Issue by cgpeter96** [arXiv/html_feedback#561]
### Description

RT

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

94b4a1f1-70bf-444b-a7a9-9c7c15fef4c5

### Paper URL

https://arxiv.org/html/2401.12954v1

### Browser

Chrome/121.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
