### ISSUE TITLE
 Section references failed

### ISSUE THREAD

**Issue by Lawhy** [arXiv/html_feedback#566]
### Description

The links to individual sections shown on the left ToC failed and the 404 page showed up.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

09337379-da1b-4e95-a921-1814235b3005

### Paper URL

https://arxiv.org/html/2401.11374v1

### Browser

Chrome/120.0.0.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
