### ISSUE TITLE
Images are not rendered when overpic -- LaTeX environment -- is used

### ISSUE THREAD

**Issue by reinhardgrassmann** [arXiv/html_feedback#568]
### Description

Images are not rendered. Only the LaTeX code is shown.

### (Optional:) Please add any files, screenshots, or other information here.

![image](https://github.com/arXiv/html_feedback/assets/62680573/3ca8b9dc-ce2d-48f4-b053-07e600ec321b)

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

d176053b-7c70-4b53-9adc-f8a1d544c37d

### Paper URL

https://arxiv.org/html/2402.14175v1

### Browser

Firefox/122.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Is /overpic provided by the epic package? Epic is not currently supported (as noted in the banner). It is in the top-10 most-requested for latexml support (https://github.com/brucemiller/LaTeXML/wiki/Porting-LaTeX-packages-for-LaTeXML) so I hope the latexml project is able to support it eventually.

**Comment by reinhardgrassmann** [comment]
Thanks for letting me know about the current state. I will pass this on to my lab members.
