### ISSUE TITLE
 Not able to find input dataset.tsv

### ISSUE THREAD

**Issue by SaileeDas** [arXiv/html_feedback#577]
### Description

Could not find input dataset.tsv.Please share the path of the file in the project

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

fcae201f-a000-4911-9f86-a912125bce1f

### Paper URL

https://arxiv.org/html/2402.11910v1

### Browser

Chrome/122.0.0.0

### Device Type

Windows

**Comment by dginev** [comment]
I suspect this should be a question addressed at the document authors. Thanks!
