### ISSUE TITLE
 The TOC links don't work

### ISSUE THREAD

**Issue by dylanjcastillo** [arXiv/html_feedback#589]
### Description

When you click on a section in the TOC it leads to a 404 error.

### (Optional:) Please add any files, screenshots, or other information here.

<img width="1512" alt="image" src="https://github.com/arXiv/html_feedback/assets/7218756/44c35daf-6441-438f-972c-01ba3edb676e">

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

64a5d183-54c7-4913-8300-d743ff7c9c51

### Paper URL

https://arxiv.org/html/2401.10506v1

### Browser

Firefox/123.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Thanks for your report. We have fixed this issue in new conversions and will recreate the HTML for existing papers when the next version of LaTeXML is released. I rebuilt the HTML for this paper with the updated converter, and it now appears to work. Thank you for bringing this to our attention - we rely on feedback reports to help prioritize improvements to the html conversions. I will close this issue report -- if the issue persists, please let me know.
