### ISSUE TITLE
 DOI is missing

### ISSUE THREAD

**Issue by JoernLoviscach** [arXiv/html_feedback#595]
### Description

The traditional interface gave a DOI URL. I can't find that any more.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

52a22896-d13a-4954-a02c-376da6f33bf0

### Paper URL

https://arxiv.org/html/2402.10949v2

### Browser

Chrome/122.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
@JoernLoviscach I think you need to visit the abstract page:
https://arxiv.org/abs/2402.10949v2
