### ISSUE TITLE
 Incorrect double-quote matching (all right-curly quotes)

### ISSUE THREAD

**Issue by gwern** [arXiv/html_feedback#645]
### Description

All of the quote pairs in these paragraphs are wrong: instead of “foo”, it's just ”foo”.

### (Optional:) Please add any files, screenshots, or other information here.

![xwd-17098251202075164](https://github.com/arXiv/html_feedback/assets/352559/1b065268-f317-4e1f-9821-1c0988eca048)

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

5e7bf05b-6d41-418c-a6d3-b786203770fe

### Paper URL

https://arxiv.org/html/2402.07043v1

### Browser

Firefox/123.0

### Device Type

Desktop

**Comment by chrisjcameron** [comment]
Well spotted! Unfortunately, this is a mistake in the original LaTeX source. Both the HTML and PDF faithfully render the quotes as the author mis-specified.
