### ISSUE TITLE
 Garbled word in article about computational supremacy

### ISSUE THREAD

**Issue by sttaft** [arXiv/html_feedback#678]
### Description

In both this paragraph and the next, the word "ansätze" appears.  It is not clear what word was meant.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

14d853ba-5d2c-4aeb-88db-d74701a16fc3

### Paper URL

https://arxiv.org/html/2403.00910v1

### Browser

Firefox/123.0

### Device Type

Desktop

**Comment by dginev** [comment]
This appears to be feedback for the authors - please send it their way, as this repository only collects feedback on the quality of the experimental HTML output. Thanks!
