### ISSUE TITLE
 Incorrect Translation of "Abstract"

### ISSUE THREAD

**Issue by icm-ai** [arXiv/html_feedback#703]
### Description

The term "abstract" in the context of documents and articles should be translated as "摘要" rather than "抽象的". The former is the correct term for a brief summary or overview of a longer piece of work, which is the intended meaning of "abstract" in academic and professional settings. The latter, "抽象的", translates to "abstract" in the sense of being theoretical or not concrete, which is not the intended usage in this context.This is a straightforward translation issue that affects the clarity and 

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

c1145a85-d23c-4d37-bf44-710a173a390e

### Paper URL

https://arxiv.org/html/2401.02415v1?_immersive_translate_auto_translate=1

### Browser

Chrome/122.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
@icm-ai please forward this feedback to the team of your translation tool. 

This repository collects issues with the main HTML format. Thanks!
