### ISSUE TITLE
 HTML display errors

### ISSUE THREAD

**Issue by notuntoward** [arXiv/html_feedback#769]
### Description

Every time I'm directed to  this site, I see this error message:HTML conversions sometimes display errors due to content that did not convert correctly from the source. This paper uses the following packages that are not yet supported by the HTML conversion tool. Feedback on these issues are not necessary

### (Optional:) Please add any files, screenshots, or other information here.

![image](https://github.com/arXiv/html_feedback/assets/3851891/a3885fe9-962d-44ae-a729-96c49418dcb3)

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

047b700b-81c6-456b-bed5-f814d3576846

### Paper URL

https://arxiv.org/html/2403.07815v1

### Browser

Chrome/122.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Yes, this is intended behavior for the current experimental stage of HTML papers. 

Thank you for writing in!
