### ISSUE TITLE
 Duplicate content

### ISSUE THREAD

**Issue by cndpzc** [arXiv/html_feedback#847]
### Description

The content selected is duplicated.

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

34b60928-1f6c-43a3-96a8-ba97e98152bc

### Paper URL

https://arxiv.org/html/2312.07769v1

### Browser

Chrome/122.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
@cndpzc isn't this also the case in the PDF?

https://arxiv.org/pdf/2312.07769v1

It may be worth informing the authors, who can push a v2 with a correction. I see that the exact code you mention is duplicated in the `main.tex` source as well.

**Comment by dginev** [comment]
Please let the authors know, as this appears to be an error with the source document.
