### ISSUE TITLE
Plagiarism
The article is repeating an ieee idea exactly without citing it 
The article is "PremiUm-CNN: Propagating Uncertainty Towards Robust Convolutional Neural Networks." It is a clear plagiarism that should be reported.


### ISSUE THREAD

**Issue by dimahdera** [arXiv/html_feedback#848]
The article is repeating an ieee idea exactly without citing it 
The article is "PremiUm-CNN: Propagating Uncertainty Towards Robust Convolutional Neural Networks." It is a clear plagiarism that should be reported.

**Comment by chrisjcameron** [comment]
We see the related ticket in the user help system, so I will close this github issue. Thank you for taking the time to report!

**Comment by dimahdera** [comment]
So, you will close it with no action?
