### ISSUE TITLE
 Properties of hypergeometric function

### ISSUE THREAD

**Issue by PawanGu** [arXiv/html_feedback#865]
### Description

Hi, I am wondering what propertied of hypergeometric functions has been used to obtain this expression.

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

5a299775-c0a3-449d-8ab4-2bd1eb2d66dd

### Paper URL

https://arxiv.org/html/2312.05065v1

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Please contact the authors for questions on the substance of the text. 

This repository only collects reports for the quality of the experimental HTML format.
