### ISSUE TITLE
Wrong default font weight

### ISSUE THREAD

**Issue by ofou** [arXiv/html_feedback#881]
### Description

I think `[ltx_page_content](font-weight: 300;)` is wrong. It displays the whole content with thinner fonts. It should use normal font weights for the page content. 

### (Optional:) Please add any files, screenshots, or other information here.

- Before
 ![Original](https://github.com/arXiv/html_feedback/assets/12256669/9a2b1ab8-8b7f-4e00-9f67-3d7825b2817c)
- After 
![Normal weight](https://github.com/arXiv/html_feedback/assets/12256669/0b76e655-f05d-485f-a9fe-bc0ee73f310e)

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

4c46481b-748d-4ab8-b959-896d95b99149

### Paper URL

https://arxiv.org/html/2403.16971v2

### Browser

Firefox/115.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for the report. We've changed to `RivalSans-Light` where 300 works as expected.

**Comment by ofou** [comment]
Awesome, thanks :) @dginev
