### ISSUE TITLE
Incomplete figure display 

### ISSUE THREAD

**Issue by ShenhanQian** [arXiv/html_feedback#887]
### Description

Figure 3, 4, 5, and 7 in the paper are incomplete. The lowerhalf of the figures are missing.

### (Optional:) Please add any files, screenshots, or other information here.

![image](https://github.com/arXiv/html_feedback/assets/23174052/f4c16dff-fadd-495c-979c-3e1cd330eeba)
![image](https://github.com/arXiv/html_feedback/assets/23174052/5169a6e3-2e27-4153-8dcd-e0ced833b177)
![image](https://github.com/arXiv/html_feedback/assets/23174052/c1c665bf-02c2-48de-8f7c-44f081e955fe)
![image](https://github.com/arXiv/html_feedback/assets/23174052/6210e473-a8ac-42e5-ba5c-027f3210d670)

### (Required) What is this issue most closely related to? Select one.

Figures

### Internal issue ID

38e7b548-8971-4007-b42c-ad8ec7189a01

### Paper URL

https://arxiv.org/html/2312.02069v2

### Browser

Chrome/122.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for your report - the specific issue is now solved.

We have regenerated the article and you should be able to see an improvement.
