### ISSUE TITLE
 colored text should be uncolored 

### ISSUE THREAD

**Issue by Andron00e** [arXiv/html_feedback#913]
### Description

remove \textcolor{blue}{the} with "the"

### (Optional:) Please add any files, screenshots, or other information here.

<img width="615" alt="Screenshot 2024-04-05 at 12 48 57" src="https://github.com/arXiv/html_feedback/assets/67924720/42230c0e-bcca-444a-b40e-e3b9f9888c1d">

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

ea1846d3-cfc5-40b3-9387-c0b5ab4f7cdd

### Paper URL

https://arxiv.org/html/2404.03323v1

### Browser

Chrome/123.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
@Andron00e this HTML behavior is the same as with the PDF file.

Given you're an author, maybe push a version 2 update that removes the color?
